### ISSUE TITLE
Source Sans Pro TTF files do not include Smallcaps

### ISSUE THREAD

**Issue by psykon** [mintyfrankie/brilliant-CV#17]
**Describe the bug**
When rendering the project with the included fonts at src/fonts, the output does not show the smallcaps as it is the case in the screenshots.

**To Reproduce**
1. Clone Repository
2. build with just compile-cv
3. Inspect PDF

**Expected behavior**
Societies and Footer to be rendered in SmallCaps

**Possible Fix**
It seems that Adobe included SmallCaps only in the OpenType version of the Fonts, not the TrueType versions.
Adding the OTF files from https://github.com/adobe-fonts/source-sans to the src/fonts directory and changing the font in template.typ to "Source Sans 3" leads to an output with correctly rendered SmallCaps - while everything else looks the same (at least on my machine)

**Comment by mintyfrankie** [comment]
Hi @psykon excuses for the long-due follow-up, just checked and indeed this is not an expected behaviour (I didn't even realize the question of small-caps). 

I see two solutions:
1. Replace the ttf files with the ones including Smallcaps
2. De-style all the smallcaps and replace them by normal fontstyle

Which one in your opinion can be more desirable?

**Comment by psykon** [comment]
Personally, I really like the look of SmallCaps in the template, so I would prefer to keep the style and go with option 1.

**Comment by mintyfrankie** [comment]
New font files updated! Closing this issue and pls check if it works well on your side!
