### ISSUE TITLE
Single language version

### ISSUE THREAD

**Issue by ericthomasca** [mintyfrankie/brilliant-CV#48]
This could be easier to use in a single language. Will look at this later in future.

**Comment by mintyfrankie** [comment]
Can I elaborate more on that please? For the time being, single language usage can be achieved by just having one `modules` folder, and with only one section of `lang` in `metadata.toml`.

It is not the cleanest for sure, but since this template was designed since the very first beginning to support multilingual usage, I think it is part of the unique value proposition. 

A "default" language might be set in theory, but things can get quite hacky.

**Comment by ericthomasca** [comment]
I was just thinking there could be a version where there would just be a `modules` folder. There are other things to work on at this time. Feel free to close this, just a suggestion for possible future.
