### ISSUE TITLE
Font characteristics should be configurable

### ISSUE THREAD

**Issue by munzirtaha** [mintyfrankie/brilliant-CV#58]
After thankfully fixing issue #55, font characteristics as well should be configurable.

This bug is not about adding more configurations but about making already available configurations public and configurable by the user.
e.g. the code

```
let headerLastNameStyle(str) = {text(font: headerFont, size: 32pt, weight: "bold", str)}
let headerInfoStyle(str) = {text(size: 10pt, fill: accentColor, str)}
let headerQuoteStyle(str) = {text(size: 10pt, weight: "medium", style: "italic", fill: accentColor, str)
```

is already there. In the original `Awesome-CV` which inspired this project and even the old version of this project, configuring all these things is very easy and nothing is hidden deep from the user.

Not all the fonts have the same `size`, not all the fonts have the `medium` weight or the italic style. This should all be configurable.

**Comment by mintyfrankie** [comment]
Let's make it clear here Munzir, it's not a "bug", but rather an opinionated choice.

For a template, the developer should balance between flexibility and simplicity. The idea here is that I don't want to leave too many options to the users, otherwise to a point where we can simply write the template on our own.

Font sizes are indeed hardcoded, just as the original LaTeX template does. If these settings can be adjusted by the users via `metadata.toml`, there will be like more than 20 more fields of option, which is not desirable for me.

I am discussing with the developer of [utpm](https://github.com/Thumuss/utpm) to work on a feature that allows users to "clone" the upstream template and modify the codes as they wish locally, I think this can help with your need to have more control on the template (See [issue](https://github.com/Thumuss/utpm/issues/25)).

So this is not going to be "fixed" for the time being. However, any contribution to solve this issue elegantly is much welcomed!

**Comment by Thumuss** [comment]
> I am discussing with the developer of [utpm](https://github.com/Thumuss/utpm) to work on a feature that allows users to "clone" the upstream template and modify the codes as they wish locally, I think this can help with your need to have more control on the template (See [issue](https://github.com/Thumuss/utpm/issues/25)).

I confirm that we are testing cloning on package, see [this PR too](https://github.com/Thumuss/utpm/pull/27) to know how to use it. If you need anything I'm always here.

**Comment by munzirtaha** [comment]
Thanks for both of you for your great work and follow-up. I, myself, couldn't even installed `utpm` as per my comment on #55 . But since @Thumuss himself is here may be he tell me what am I doing wrong.

**Comment by Thumuss** [comment]
> Thanks for both of you for your great work and follow-up. I, myself, couldn't even install `utpm` as per my comment on #55 . But since @Thumuss himself is here may be he tell me what am I doing wrong.

Sure! What's the problem? Do you have the log?

**Comment by munzirtaha** [comment]
@Thumuss: Thanks so much, it worked now.

@mintyfrankie: Now, I see that I can edit the template directly in the '~/.cache' directory. Wouldn't this resolve all of my issues? If so, this is what I'm asking for, not that you overwrite the functions with new code and complicate the package. It could all be a misunderstanding. Could you please explain what 'utpm' PR would add to this workflow?

**Comment by mintyfrankie** [comment]
Great to hear!

Indeed we might have a misalignment here -- you can always edit the source files in your local workspace, it's just that with the Typst package system design, they are hided deep down somewhere in your system, which is not that convenient at all.

I will let you discuss with @Thumuss if you have any specific needs for the wonderful `utpm` tool, he is very reactive and supportive. Basically `utpm` tries to make your life easier, without having to navigating between `~/.cache`, symlinks, etc.

**Comment by munzirtaha** [comment]
For me as far as I know which file to change, it doesn't make a difference where is it located so I will close this for now. Thanks all
