### ISSUE TITLE
Set before*Skip variable from top cv.typ file 

### ISSUE THREAD

**Issue by barbem** [mintyfrankie/brilliant-CV#8]
Hi,
I would like to override beforeSectionSkip, beforeEntrySkip and beforeEntryDescriptionSkip variables defined in awesomeCV/template.typ.

Is it possible to do this without editing the template.typ file (do this from cv.typ file)?

Thank you.

**Comment by mintyfrankie** [comment]
Hi @barbem, thanks for bringing this up!

This could be a bit complicated due to the current topologies of this project (interoperability between `template`, `metadata` and `cv`/`letter`) and also the evolution of Typst development, for me it is still unclear how to best balance between customization and usability. So I will not expose these two parameters outside of `template.typ` for the time being.

But in my own CV I often change these two variables to stretch or shrink the CV page, so it is indeed a hack. You are encouraged to manually change them in `template.typ`, until a better solution can be discussed. 

I will leave this issue open and anyone is welcomed to come up with an idea about how to better managing variables.

**Comment by tinnet** [comment]
@barbem not sure if this is what you're aiming at but if all you want is not to have bullet points (or different ones) in the experience section, you can override how list works (https://typst.app/docs/reference/layout/list/#parameters-marker):

```typst
#cvSection("Experience")

// no list indent for this section!
#set list(marker: [])
```

**Comment by mintyfrankie** [comment]
Closing this issue as it stays inactive for a long time. Don't hesitate to reopen!
